language: node_js

node_js:
  - 0.10

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install
  # Install and build all sub-projects.
  # ======= full/amd =======
  - cd full/amd
  - npm install
  - cd ../..
  # ======= skeleton/amd =======
  - cd skeleton/amd
  - npm install
  - cd ../..
  # ======= full/browserify =======
  - cd full/browserify
  - npm install
  - cd ../..
  # ======= skeleton/browserify =======
  - cd skeleton/browserify
  - npm install
  - cd ../..
  # ======= full/webpack-cls =======
  - cd full/webpack-cls
  - ./node_modules/.bin/gulp build
  - ./node_modules/.bin/gulp build:dev
  - cd ../..

script:
  # Root level checks.
  - ./node_modules/.bin/gulp check:ci
  # Sub-project checks.
  # ======= full/amd =======
  - cd full/amd
  - ./node_modules/.bin/grunt check:ci
  - cd ../..
  # ======= skeleton/amd =======
  - cd skeleton/amd
  - ./node_modules/.bin/grunt check:ci
  - cd ../..
  # ======= full/browserify =======
  - cd full/browserify
  - ./node_modules/.bin/grunt check:ci
  - cd ../..
  # ======= skeleton/browserify =======
  - cd skeleton/browserify
  - ./node_modules/.bin/grunt check:ci
  - cd ../..
  # ======= full/webpack-cls =======
  - cd full/webpack-cls
  - ./node_modules/.bin/gulp check:ci
  - cd ../..
