language: node_js

node_js:
  - 0.10

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install
  # Install and build all sub-projects.
  - cd full/amd
  - npm install
  - cd ../..
  - cd skeleton/amd
  - npm install
  - cd ../..
  - cd full/browserify
  - npm install
  - cd ../..
  - cd skeleton/browserify
  - npm install
  - cd ../..
  # Check production build actually works.
  - ./node_modules/.bin/gulp build
  # Overwrite with dev build for tests, etc.
  - ./node_modules/.bin/gulp build:dev

script:
  # Root level checks.
  - ./node_modules/.bin/gulp check:ci
  # Sub-project checks.
  - cd full/amd
  - ./node_modules/.bin/grunt check:ci
  - cd ../..
  - cd skeleton/amd
  - ./node_modules/.bin/grunt check:ci
  - cd ../..
  - cd full/browserify
  - ./node_modules/.bin/grunt check:ci
  - cd ../..
  - cd skeleton/browserify
  - ./node_modules/.bin/grunt check:ci
  - cd ../..
